"""All user-facing UI strings in the 5 languages, so a language switch changes the whole app.
Any key missing in a language falls back to English on the frontend."""

STRINGS = {
    "en": {
        "nav_home": "Home", "nav_app": "Size now", "chooseLang": "🌍 Choose your language",
        "signin": "Sign in", "myResults": "My results", "logout": "Log out",
        "theme_dark": "Dark mode", "theme_light": "Light mode",
        "tour_start": "Quick tour", "tour_next": "Next", "tour_skip": "Skip", "tour_done": "Got it",
        "tour_lang": "Switch anytime. The whole app and the spoken plan follow.",
        "home_h1": "Power your home with the sun, in your language",
        "home_sub": "Say your appliances out loud. Get your exact solar system, drawn in 2D and 3D, and spoken back to you.",
        "cta_size": "☀️ Size your system free", "cta_how": "See how it works",
        "stat_langs": "5 languages", "stat_models": "Models under 4B", "stat_free": "Free to use",
        "prob_h": "Solar should be simple. It usually isn't.",
        "prob_1": "About 90 million Nigerians have no reliable power, and burn billions on generators.",
        "prob_2": "Quotes come in English, full of jargon like kVA, that most people can't act on.",
        "prob_3": "So the people who would gain the most are the ones solar never speaks to.",
        "how_h": "How it works", "how_1t": "Say it", "how_1s": "Speak, type, or snap a photo, in your own language.",
        "how_2t": "It sizes it", "how_2s": "Exact panels, inverter and battery, over real Nigerian prices.",
        "how_3t": "See it", "how_3s": "Your home in 2D and an explorable 3D, with a clear plan.",
        "how_4t": "Hear it", "how_4s": "Your full result, read aloud in your language.",
        "testi_h": "What people are saying", "testi_sub": "Real feedback from people who sized their homes.",
        "why_h": "Small models, real impact",
        "why_s": "Every model is under 4 billion parameters and self-hosted, so it stays cheap and fast for everyone.",
        "final_h": "Ready to leave the generator behind?", "final_cta": "☀️ Size your system now",
        "back_home": "← Home",
        "speak": "Speak your appliances", "speak_sub": "tap Record, speak, tap Stop",
        "record": "Record", "stop": "Stop", "voicehint": "It transcribes and sizes itself.",
        "type": "Or type them", "sizeit": "Size it",
        "ex_h": "New here? Tap an example", "ex_sub": "a full result in one click",
        "ex_home": "🏠 Small home", "ex_shop": "🏪 Corner shop", "ex_family": "👨‍👩‍👧 Family house",
        "photo": "Or snap / upload photos", "photo_drop": "Tap to add photos of your room (up to 5)",
        "new_sizing": "🔄 Size another system", "photo_spotted": "From your photo, we spotted", "photo_adjust": "Not quite right? Adjust the appliances below.",
        "detect": "Detect appliances from photo",
        "tab_3d": "🏠 3D Home", "tab_2d": "🖼️ 2D View", "tab_sys": "⚡ System",
        "hd_3d": "Your home in 3D", "hd_3d_sub": "drag to look around · scroll to zoom",
        "hear": "Your plan, in your language",
        "narr_loading": "Preparing the voice…",
        "narr_fail": "The voice is taking a moment. You can read your plan above, or use the play button.",
        "adj": "🛠️ Adjust appliances", "add": "➕ Add", "clear": "Clear", "update": "Update sizing",
        "pick": "Pick an appliance…",
        "askt": "💬 Ask about your system", "ask_ph": "e.g. Why these panels? Can it run my AC at night?", "ask_btn": "Ask",
        "where": "🛒 Where to buy", "loc_btn": "Use my location",
        "fb_acc": "💛 Was this helpful? Get updates", "fb_ph": "Any comment to help us improve? (optional)",
        "fb_up": "👍 Helpful", "fb_down": "👎 Could be better",
        "email_hint": "📩 Want solar tips, or your result saved? Add your email, optional and no spam.",
        "email_ph": "you@email.com", "notify": "Notify me",
        "footer": "Estimates from current Nigerian prices. Confirm with a licensed installer. · Built in Lagos ☀️",
        "acc_create": "Create your account", "acc_welcome": "Welcome back",
        "acc_create_sub": "Save your sizings and pick up where you left off, anytime.",
        "acc_welcome_sub": "Sign in to see your saved results.",
        "f_name": "Your name", "f_pass": "Password (6+ characters)",
        "btn_create": "Create account", "btn_signin": "Sign in",
        "have_acc": "Already have an account?", "new_here": "New here?",
        "link_signin": "Sign in", "link_create": "Create an account",
        "saved": "Saved to your results", "save_prompt": "Sign in to save this result and come back to it",
        "hist_h": "Your saved results", "hist_sub": "Tap any result to open it again.",
        "hist_empty": "No saved results yet. Size a system and it will appear here.",
        "rate_h": "How was your result?", "rate_sub": "Your rating helps others trust it.",
        "rate_ph": "Add a word about your experience (optional)", "rate_send": "Send rating", "rate_thanks": "Thank you! 🙏",
    },
    "pcm": {
        "nav_home": "Home", "nav_app": "Size am now", "chooseLang": "🌍 Choose your language",
        "signin": "Sign in", "myResults": "My results", "logout": "Comot",
        "theme_dark": "Dark mode", "theme_light": "Bright mode",
        "tour_start": "Quick tour", "tour_next": "Next", "tour_skip": "Comot", "tour_done": "I don sabi",
        "tour_lang": "Change am anytime. The whole app and the voice go follow.",
        "home_h1": "Power your house with sun, for your own language",
        "home_sub": "Just talk your appliances. You go get your correct solar system, we go draw am for 2D and 3D, and yarn am give you.",
        "cta_size": "☀️ Size your system free", "cta_how": "See how e dey work",
        "stat_langs": "5 languages", "stat_models": "Models wey small pass 4B", "stat_free": "Free to use",
        "prob_h": "Solar suppose easy. But e no dey.",
        "prob_1": "Like 90 million Naija people no get steady light, dem dey waste billions for generator.",
        "prob_2": "Quote dey come for English, full of big grammar like kVA, wey plenty people no fit use.",
        "prob_3": "So na the people wey need am pass solar never yarn.",
        "how_h": "How e dey work", "how_1t": "Talk am", "how_1s": "Talk, type, or snap photo, for your own language.",
        "how_2t": "E go size am", "how_2s": "Correct panel, inverter and battery, with real Naija price.",
        "how_3t": "See am", "how_3s": "Your house for 2D and 3D wey you fit turn, with clear plan.",
        "how_4t": "Hear am", "how_4s": "Your full result, we go yarn am for your language.",
        "testi_h": "Wetin people dey talk", "testi_sub": "Real feedback from people wey don size dem house.",
        "why_h": "Small models, real impact",
        "why_s": "Every model small pass 4 billion parameters, we host am ourself, so e dey cheap and fast for everybody.",
        "final_h": "You ready to leave generator?", "final_cta": "☀️ Size your system now",
        "back_home": "← Home",
        "speak": "Talk your appliances", "speak_sub": "press Record, talk, press Stop",
        "record": "Record", "stop": "Stop", "voicehint": "E go hear am and size am.",
        "type": "Or type am", "sizeit": "Size am",
        "ex_h": "You new? Tap example", "ex_sub": "full result for one click",
        "ex_home": "🏠 Small house", "ex_shop": "🏪 Shop", "ex_family": "👨‍👩‍👧 Family house",
        "photo": "Or snap / upload photo", "photo_drop": "Tap to add photo of your room (reach 5)",
        "new_sizing": "🔄 Size another one", "photo_spotted": "From your photo, we see", "photo_adjust": "E no correct? Change the appliances for down.",
        "detect": "Detect appliances from photo",
        "tab_3d": "🏠 3D House", "tab_2d": "🖼️ 2D View", "tab_sys": "⚡ System",
        "hd_3d": "Your house for 3D", "hd_3d_sub": "drag to look · scroll to zoom",
        "hear": "Your plan, for your language",
        "narr_loading": "We dey prepare the voice…",
        "narr_fail": "The voice dey take small time. You fit read your plan for up, or press play.",
        "adj": "🛠️ Adjust appliances", "add": "➕ Add", "clear": "Clear", "update": "Update sizing",
        "pick": "Pick appliance…",
        "askt": "💬 Ask about your system", "ask_ph": "like Why these panels? E fit run my AC for night?", "ask_btn": "Ask",
        "where": "🛒 Where to buy", "loc_btn": "Use my location",
        "fb_acc": "💛 E helep? Get updates", "fb_ph": "Any comment to make am better? (optional)",
        "fb_up": "👍 E helep", "fb_down": "👎 E fit beta",
        "email_hint": "📩 You want solar tips, or save your result? Drop your email, optional, no spam.",
        "email_ph": "you@email.com", "notify": "Notify me",
        "footer": "Na estimate from current Naija price. Confirm with one licensed installer. · Built for Lagos ☀️",
        "acc_create": "Create your account", "acc_welcome": "Welcome back",
        "acc_create_sub": "Save your sizings make you fit continue anytime.",
        "acc_welcome_sub": "Sign in make you see your saved results.",
        "f_name": "Your name", "f_pass": "Password (6+ letters)",
        "btn_create": "Create account", "btn_signin": "Sign in",
        "have_acc": "You get account before?", "new_here": "You new?",
        "link_signin": "Sign in", "link_create": "Create account",
        "saved": "We don save am for your results", "save_prompt": "Sign in make we save this result for you",
        "hist_h": "Your saved results", "hist_sub": "Tap any result make e open again.",
        "hist_empty": "No saved result yet. Size system and e go show here.",
        "rate_h": "How your result be?", "rate_sub": "Your rating dey help others trust am.",
        "rate_ph": "Talk small about your experience (optional)", "rate_send": "Send rating", "rate_thanks": "Thank you! 🙏",
    },
    "yo": {
        "nav_home": "Ilé", "nav_app": "Wọ̀n ún", "chooseLang": "🌍 Yan èdè rẹ",
        "signin": "Wọlé", "myResults": "Àbájáde mi", "logout": "Jáde",
        "theme_dark": "Ipò òkùnkùn", "theme_light": "Ipò ìmọ́lẹ̀",
        "tour_start": "Ìrìn àgbéyẹ̀wò", "tour_next": "Tókàn", "tour_skip": "Fò ó", "tour_done": "Ó yé mi",
        "tour_lang": "Yí i padà nígbàkigbà. Gbogbo ohun àti ohùn náà á tẹ̀lé.",
        "home_h1": "Fi oòrùn pèsè iná ilé rẹ, ní èdè rẹ",
        "home_sub": "Sọ àwọn ohun-èlò rẹ. Gba ètò oòrùn pípé, a ó yà á ní 2D àti 3D, a ó sì sọ ọ́ fún ọ.",
        "cta_size": "☀️ Wọ̀n ètò rẹ lọ́fẹ̀ẹ́", "cta_how": "Wo bí ó ṣe ń ṣiṣẹ́",
        "stat_langs": "Èdè márùn-ún", "stat_models": "Àwòṣe tó kéré sí 4B", "stat_free": "Lọ́fẹ̀ẹ́",
        "prob_h": "Oòrùn yẹ kó rọrùn. Ṣùgbọ́n kò rí bẹ́ẹ̀.",
        "prob_1": "Nǹkan bí mílíọ̀nù 90 ọmọ Nàìjíríà kò ní iná tó dúró ṣinṣin.",
        "prob_2": "Owó wọn máa ń wà ní Gẹ̀ẹ́sì, pẹ̀lú ọ̀rọ̀ líle bí kVA, tí ọ̀pọ̀ kò lè lò.",
        "prob_3": "Nítorí náà àwọn tó nílò rẹ̀ jù ni oòrùn kò bá sọ̀rọ̀.",
        "how_h": "Bí ó ṣe ń ṣiṣẹ́", "how_1t": "Sọ ọ́", "how_1s": "Sọ, kọ, tàbí ya fọ́tò, ní èdè rẹ.",
        "how_2t": "Yóò wọ̀n ún", "how_2s": "Panel, inverter àti batiri pípé, lórí owó ọjà Nàìjíríà.",
        "how_3t": "Wò ó", "how_3s": "Ilé rẹ ní 2D àti 3D tí o lè yí, pẹ̀lú ètò tó ṣe kedere.",
        "how_4t": "Gbọ́ ọ", "how_4s": "Àbájáde rẹ, a ó kà á sókè ní èdè rẹ.",
        "testi_h": "Ohun tí àwọn ènìyàn ń sọ", "testi_sub": "Èsì tòótọ́ láti ọ̀dọ̀ àwọn tó ti wọ̀n ilé wọn.",
        "why_h": "Àwòṣe kékeré, ipa gidi",
        "why_s": "Gbogbo àwòṣe kéré sí bílíọ̀nù mẹ́rin parameters, a sì gbà á lọ́wọ́ ara wa, kó lè dín owó kù kó sì yára fún gbogbo ènìyàn.",
        "final_h": "Ṣé o ti ṣetán láti fi ẹ̀rọ-iná sílẹ̀?", "final_cta": "☀️ Wọ̀n ètò rẹ báyìí",
        "back_home": "← Ilé",
        "speak": "Sọ àwọn ohun-èlò rẹ", "speak_sub": "tẹ Record, sọ̀rọ̀, tẹ Stop",
        "record": "Gbasilẹ̀", "stop": "Dúró", "voicehint": "Yóò gbọ́ ọ yóò sì wọ̀n ún.",
        "type": "Tàbí kọ wọ́n", "sizeit": "Wọ̀n ún",
        "ex_h": "Tuntun? Tẹ àpẹẹrẹ", "ex_sub": "àbájáde kíkún ní títẹ̀ kan",
        "ex_home": "🏠 Ilé kékeré", "ex_shop": "🏪 Ṣọ́ọ̀bù", "ex_family": "👨‍👩‍👧 Ilé ìdílé",
        "photo": "Tàbí ya / fi fọ́tò sí", "photo_drop": "Tẹ láti fi fọ́tò yàrá rẹ sí (tó 5)",
        "new_sizing": "🔄 Wọ́n ètò mìíràn", "photo_spotted": "Nínú fọ́tò rẹ, a rí", "photo_adjust": "Kò tọ̀nà bí? Ṣàtúnṣe àwọn ohun-èlò nísàlẹ̀.",
        "detect": "Wá àwọn ohun-èlò nínú fọ́tò",
        "tab_3d": "🏠 Ilé 3D", "tab_2d": "🖼️ Wíwò 2D", "tab_sys": "⚡ Ètò",
        "hd_3d": "Ilé rẹ ní 3D", "hd_3d_sub": "fà láti wò · yí láti sún",
        "hear": "Ètò rẹ, ní èdè rẹ",
        "narr_loading": "À ń pèsè ohùn náà…",
        "narr_fail": "Ohùn náà ń lo àkókò díẹ̀. O lè ka ètò rẹ lókè, tàbí tẹ bọ́tìnì ìṣeré.",
        "adj": "🛠️ Ṣàtúnṣe ohun-èlò", "add": "➕ Fi kún", "clear": "Pa rẹ́", "update": "Tún wọ̀n ún",
        "pick": "Yan ohun-èlò…",
        "askt": "💬 Béèrè nípa ètò rẹ", "ask_ph": "bíi Kí ló dé panel wọ̀nyí? Ṣé ó lè ṣiṣẹ́ AC mi lóru?", "ask_btn": "Béèrè",
        "where": "🛒 Ibi tí o ti lè rà á", "loc_btn": "Lo ibi tí mo wà",
        "fb_acc": "💛 Ṣé ó wúlò? Gba ìròyìn", "fb_ph": "Ọ̀rọ̀ kankan láti mú un dára síi? (kì í ṣe dandan)",
        "fb_up": "👍 Ó wúlò", "fb_down": "👎 Ó lè dára síi",
        "email_hint": "📩 Ṣé o fẹ́ ìmọ̀ràn oòrùn, tàbí pa àbájáde rẹ mọ́? Fi ímeèlì rẹ sí, kì í ṣe dandan.",
        "email_ph": "you@email.com", "notify": "Sọ fún mi",
        "footer": "Ìfojúsùn láti owó ọjà Nàìjíríà. Jẹ́rìí pẹ̀lú òṣìṣẹ́ tó ní ìwé-àṣẹ. · A kọ́ ọ ní Èkó ☀️",
        "acc_create": "Ṣẹ̀dá àkàǹtì rẹ", "acc_welcome": "Káàbọ̀ padà",
        "acc_create_sub": "Pa àwọn ìwọ̀n rẹ mọ́ kí o sì tẹ̀síwájú nígbàkígbà.",
        "acc_welcome_sub": "Wọlé láti rí àwọn àbájáde rẹ tí o pamọ́.",
        "f_name": "Orúkọ rẹ", "f_pass": "Ọ̀rọ̀ aṣínà (6+)",
        "btn_create": "Ṣẹ̀dá àkàǹtì", "btn_signin": "Wọlé",
        "have_acc": "Ṣé o ní àkàǹtì tẹ́lẹ̀?", "new_here": "Tuntun?",
        "link_signin": "Wọlé", "link_create": "Ṣẹ̀dá àkàǹtì",
        "saved": "A pa á mọ́ sí àbájáde rẹ", "save_prompt": "Wọlé láti pa àbájáde yìí mọ́",
        "hist_h": "Àwọn àbájáde rẹ tí o pamọ́", "hist_sub": "Tẹ àbájáde kankan láti ṣí i padà.",
        "hist_empty": "Kò sí àbájáde tí a pamọ́ síbẹ̀. Wọ̀n ètò kí ó lè hàn níbí.",
        "rate_h": "Báwo ni àbájáde rẹ?", "rate_sub": "Ìdíwọ̀n rẹ ń ran àwọn mìíràn lọ́wọ́ láti gbẹ́kẹ̀ lé e.",
        "rate_ph": "Sọ̀rọ̀ díẹ̀ nípa ìrírí rẹ (kì í ṣe dandan)", "rate_send": "Fi ìdíwọ̀n ránṣẹ́", "rate_thanks": "O ṣé! 🙏",
    },
    "ha": {
        "nav_home": "Gida", "nav_app": "Auna yanzu", "chooseLang": "🌍 Zaɓi harshenka",
        "signin": "Shiga", "myResults": "Sakamakona", "logout": "Fita",
        "theme_dark": "Yanayin duhu", "theme_light": "Yanayin haske",
        "tour_start": "Yawon kallo", "tour_next": "Na gaba", "tour_skip": "Tsallake", "tour_done": "Na gane",
        "tour_lang": "Canza kowane lokaci. Duka manhajar da muryar za su biyo.",
        "home_h1": "Samar wa gidanka wuta da rana, a harshenka",
        "home_sub": "Faɗi kayan aikinka. Ka samu cikakken tsarin hasken rana, mu zana shi a 2D da 3D, mu kuma faɗa maka.",
        "cta_size": "☀️ Auna tsarinka kyauta", "cta_how": "Duba yadda yake aiki",
        "stat_langs": "Harsuna 5", "stat_models": "Samfura ƙasa da 4B", "stat_free": "Kyauta",
        "prob_h": "Hasken rana ya kamata ya zama mai sauƙi. Amma ba haka yake ba.",
        "prob_1": "Kusan mutane miliyan 90 a Najeriya ba su da ingantacciyar wuta.",
        "prob_2": "Farashi yana zuwa da Turanci, cike da kalmomi kamar kVA, da mutane da yawa ba sa fahimta.",
        "prob_3": "Saboda haka waɗanda suka fi buƙata su ne hasken rana ba ya magana da su.",
        "how_h": "Yadda yake aiki", "how_1t": "Faɗa", "how_1s": "Faɗa, rubuta, ko ɗauki hoto, a harshenka.",
        "how_2t": "Zai auna", "how_2s": "Daidaitattun panel, inverter da batir, a kan farashin Najeriya.",
        "how_3t": "Duba", "how_3s": "Gidanka a 2D da 3D mai juyawa, da tsari bayyananne.",
        "how_4t": "Saurara", "how_4s": "Cikakken sakamakonka, za a karanta maka a harshenka.",
        "testi_h": "Abin da mutane suke faɗi", "testi_sub": "Ra'ayi na gaske daga mutanen da suka auna gidajensu.",
        "why_h": "Ƙananan samfura, tasiri na gaske",
        "why_s": "Kowane samfuri ƙasa da biliyan 4 parameters ne kuma muna gudanar da shi da kanmu, don ya yi arha kuma da sauri ga kowa.",
        "final_h": "Ka shirya barin janareta?", "final_cta": "☀️ Auna tsarinka yanzu",
        "back_home": "← Gida",
        "speak": "Faɗi kayan aikinka", "speak_sub": "danna Record, yi magana, danna Stop",
        "record": "Yi rikodi", "stop": "Tsaya", "voicehint": "Zai ji ya kuma auna.",
        "type": "Ko rubuta su", "sizeit": "Auna",
        "ex_h": "Sabo ne? Danna misali", "ex_sub": "cikakken sakamako a danni ɗaya",
        "ex_home": "🏠 Ƙaramin gida", "ex_shop": "🏪 Shago", "ex_family": "👨‍👩‍👧 Gidan iyali",
        "photo": "Ko ɗauki / ɗora hotuna", "photo_drop": "Danna ka ƙara hotunan ɗakinka (har 5)",
        "new_sizing": "🔄 Auna wani tsari", "photo_spotted": "Daga hotonka, mun ga", "photo_adjust": "Bai dai ba? Gyara kayan aiki a ƙasa.",
        "detect": "Gano kayan aiki daga hoto",
        "tab_3d": "🏠 Gida 3D", "tab_2d": "🖼️ Duba 2D", "tab_sys": "⚡ Tsari",
        "hd_3d": "Gidanka a 3D", "hd_3d_sub": "ja don dubawa · gungura don kusantarwa",
        "hear": "Tsarinka, a harshenka",
        "narr_loading": "Muna shirya muryar…",
        "narr_fail": "Muryar tana ɗaukar lokaci kaɗan. Kana iya karanta tsarinka a sama, ko ka danna play.",
        "adj": "🛠️ Gyara kayan aiki", "add": "➕ Ƙara", "clear": "Share", "update": "Sabunta aunawa",
        "pick": "Zaɓi kayan aiki…",
        "askt": "💬 Tambaya game da tsarinka", "ask_ph": "misali Me yasa waɗannan panel? Zai iya tafiyar da AC da dare?", "ask_btn": "Tambaya",
        "where": "🛒 Inda za a saya", "loc_btn": "Yi amfani da wurina",
        "fb_acc": "💛 Ya taimaka? Samu sabuntawa", "fb_ph": "Wani sharhi don inganta shi? (na zaɓi)",
        "fb_up": "👍 Ya taimaka", "fb_down": "👎 Zai iya inganta",
        "email_hint": "📩 Kana son shawarwarin hasken rana, ko a ajiye sakamakonka? Ƙara imel ɗinka, na zaɓi.",
        "email_ph": "you@email.com", "notify": "Sanar da ni",
        "footer": "Ƙididdiga daga farashin Najeriya na yanzu. Tabbatar da ƙwararren mai shigarwa. · An gina a Lagos ☀️",
        "acc_create": "Ƙirƙiri asusunka", "acc_welcome": "Barka da dawowa",
        "acc_create_sub": "Ajiye aunawarka ka ci gaba a kowane lokaci.",
        "acc_welcome_sub": "Shiga don ganin sakamakon da ka ajiye.",
        "f_name": "Sunanka", "f_pass": "Kalmar sirri (6+)",
        "btn_create": "Ƙirƙiri asusu", "btn_signin": "Shiga",
        "have_acc": "Kana da asusu?", "new_here": "Sabo ne?",
        "link_signin": "Shiga", "link_create": "Ƙirƙiri asusu",
        "saved": "An ajiye a sakamakonka", "save_prompt": "Shiga don ajiye wannan sakamako",
        "hist_h": "Sakamakon da ka ajiye", "hist_sub": "Danna kowane sakamako don buɗe shi.",
        "hist_empty": "Babu sakamako da aka ajiye tukuna. Ka auna tsari zai bayyana nan.",
        "rate_h": "Yaya sakamakonka?", "rate_sub": "Ƙimarka tana taimaka wa wasu su amince.",
        "rate_ph": "Faɗi kaɗan game da gwajinka (na zaɓi)", "rate_send": "Aika ƙima", "rate_thanks": "Na gode! 🙏",
    },
    "ig": {
        "nav_home": "Ụlọ", "nav_app": "Tụọ ugbu a", "chooseLang": "🌍 Họrọ asụsụ gị",
        "signin": "Banye", "myResults": "Nsonaazụ m", "logout": "Pụọ",
        "theme_dark": "Ọnọdụ ọchịchịrị", "theme_light": "Ọnọdụ ìhè",
        "tour_start": "Njem nlegharị", "tour_next": "Ọzọ", "tour_skip": "Mafee", "tour_done": "Aghọtala m",
        "tour_lang": "Gbanwee mgbe ọ bụla. Ngwa niile na olu ga-eso.",
        "home_h1": "Were anyanwụ nye ụlọ gị ọkụ, n'asụsụ gị",
        "home_sub": "Kwuo ngwa gị. Nweta usoro anyanwụ ziri ezi, anyị ga-ese ya na 2D na 3D, ma kwuo ya nye gị.",
        "cta_size": "☀️ Tụọ usoro gị n'efu", "cta_how": "Lee ka ọ si arụ ọrụ",
        "stat_langs": "Asụsụ ise", "stat_models": "Ụdị dị ala karịa 4B", "stat_free": "N'efu",
        "prob_h": "Anyanwụ kwesịrị ịdị mfe. Ma ọ naghị adịkarị.",
        "prob_1": "Ihe dịka nde mmadụ 90 na Naịjirịa enweghị ọkụ kwụsiri ike.",
        "prob_2": "Ọnụahịa na-abịa n'Bekee, jupụta na okwu siri ike dị ka kVA, nke ọtụtụ enweghị ike iji.",
        "prob_3": "Ya mere ndị kacha mkpa ya bụ ndị anyanwụ na-agwaghị okwu.",
        "how_h": "Ka ọ si arụ ọrụ", "how_1t": "Kwuo ya", "how_1s": "Kwuo, pịnye, ma ọ bụ sere foto, n'asụsụ gị.",
        "how_2t": "Ọ ga-atụ ya", "how_2s": "Panel, inverter na batrị ziri ezi, n'ọnụahịa Naịjirịa.",
        "how_3t": "Hụ ya", "how_3s": "Ụlọ gị na 2D na 3D ị nwere ike ịtụgharị, yana atụmatụ doro anya.",
        "how_4t": "Nụ ya", "how_4s": "Nsonaazụ gị niile, a ga-agụ ya n'asụsụ gị.",
        "testi_h": "Ihe ndị mmadụ na-ekwu", "testi_sub": "Nzaghachi n'ezie site n'aka ndị tụrụ ụlọ ha.",
        "why_h": "Obere ụdị, mmetụta n'ezie",
        "why_s": "Ụdị ọ bụla dị ala karịa ijeri 4 parameters, anyị na-elekọta ya, ka ọ dịrị ọnụ ala ma dịrị ngwa maka onye ọ bụla.",
        "final_h": "Ị dị njikere ịhapụ jenereto?", "final_cta": "☀️ Tụọ usoro gị ugbu a",
        "back_home": "← Ụlọ",
        "speak": "Kwuo ngwa gị", "speak_sub": "pịa Record, kwuo okwu, pịa Stop",
        "record": "Dekọọ", "stop": "Kwụsị", "voicehint": "Ọ ga-anụ ma tụọ ya.",
        "type": "Ma ọ bụ pịnye ha", "sizeit": "Tụọ ya",
        "ex_h": "Ọhụrụ? Pịa ihe atụ", "ex_sub": "nsonaazụ zuru oke n'otu pịa",
        "ex_home": "🏠 Obere ụlọ", "ex_shop": "🏪 Ụlọ ahịa", "ex_family": "👨‍👩‍👧 Ụlọ ezinụlọ",
        "photo": "Ma ọ bụ sere / bulite foto", "photo_drop": "Pịa tinye foto ọnụ ụlọ gị (ruo 5)",
        "new_sizing": "🔄 Tụọ usoro ọzọ", "photo_spotted": "Site na foto gị, anyị hụrụ", "photo_adjust": "Ọ zighi ezi? Dozie ngwa ndị dị n'okpuru.",
        "detect": "Chọpụta ngwa site na foto",
        "tab_3d": "🏠 Ụlọ 3D", "tab_2d": "🖼️ Nlele 2D", "tab_sys": "⚡ Usoro",
        "hd_3d": "Ụlọ gị na 3D", "hd_3d_sub": "dọrọ ka ị lee · pịgharịa ka ị mebawanye",
        "hear": "Atụmatụ gị, n'asụsụ gị",
        "narr_loading": "Anyị na-akwado olu…",
        "narr_fail": "Olu na-ewe obere oge. Ị nwere ike ịgụ atụmatụ gị n'elu, ma ọ bụ pịa play.",
        "adj": "🛠️ Dozie ngwa", "add": "➕ Tinye", "clear": "Hichapụ", "update": "Melite ntụ",
        "pick": "Họrọ ngwa…",
        "askt": "💬 Jụọ gbasara usoro gị", "ask_ph": "dịka Gịnị mere panel ndị a? Ọ ga-eji AC m n'abalị?", "ask_btn": "Jụọ",
        "where": "🛒 Ebe ị ga-azụta", "loc_btn": "Jiri ọnọdụ m",
        "fb_acc": "💛 Ọ nyeere aka? Nweta mmelite", "fb_ph": "Okwu ọ bụla iji meziwanye ya? (nhọrọ)",
        "fb_up": "👍 Ọ nyeere aka", "fb_down": "👎 Ọ ga-aka mma",
        "email_hint": "📩 Ị chọrọ ndụmọdụ anyanwụ, ma ọ bụ chekwaa nsonaazụ gị? Tinye email gị, nhọrọ.",
        "email_ph": "you@email.com", "notify": "Gwa m",
        "footer": "Atụmatụ site n'ọnụahịa Naịjirịa ugbu a. Kwado ya na onye ọrụ nwere ikike. · E wuru ya na Lagos ☀️",
        "acc_create": "Mepụta akaụntụ gị", "acc_welcome": "Nnọọ ọzọ",
        "acc_create_sub": "Chekwaa ntụ gị ma malite ebe ị kwụsịrị, mgbe ọ bụla.",
        "acc_welcome_sub": "Banye ka ị hụ nsonaazụ ndị ị chekwara.",
        "f_name": "Aha gị", "f_pass": "Okwuntughe (6+)",
        "btn_create": "Mepụta akaụntụ", "btn_signin": "Banye",
        "have_acc": "Ị nwere akaụntụ?", "new_here": "Ọhụrụ?",
        "link_signin": "Banye", "link_create": "Mepụta akaụntụ",
        "saved": "Echekwara ya na nsonaazụ gị", "save_prompt": "Banye ka ị chekwaa nsonaazụ a",
        "hist_h": "Nsonaazụ ndị ị chekwara", "hist_sub": "Pịa nsonaazụ ọ bụla iji meghee ya ọzọ.",
        "hist_empty": "Enweghị nsonaazụ echekwara. Tụọ usoro ka ọ pụta ebe a.",
        "rate_h": "Kedu ka nsonaazụ gị siri dị?", "rate_sub": "Ọ̀tụ̀tụ̀ gị na-enyere ndị ọzọ aka ịtụkwasị obi.",
        "rate_ph": "Kwuo obere ihe gbasara ahụmahụ gị (nhọrọ)", "rate_send": "Zipu ọtụtụ", "rate_thanks": "Daalụ! 🙏",
    },
}

# A few seed testimonials so the carousel is alive before real feedback arrives. Marked seed.
SEED_TESTIMONIALS = [
    {"name": "Aisha, Kano", "text": "I spoke Hausa and it told me exactly what to buy. No more confusion.", "rating": 5, "lang": "ha", "seed": True},
    {"name": "Chidi, Aba", "text": "First time I understood kVA. The 3D house made it click for my shop.", "rating": 5, "lang": "en", "seed": True},
    {"name": "Tunde, Lagos", "text": "Sized my flat in one minute by voice. The price was close to my vendor's.", "rating": 5, "lang": "yo", "seed": True},
    {"name": "Ngozi, Owerri", "text": "It read my plan back in Igbo. My mother finally understood solar.", "rating": 5, "lang": "ig", "seed": True},
    {"name": "Bola, Ibadan", "text": "Snapped a photo of my parlour and it listed everything. Brilliant.", "rating": 4, "lang": "pcm", "seed": True},
    {"name": "Emeka, Enugu", "text": "Saved three results to my account and compared them. Very useful.", "rating": 5, "lang": "en", "seed": True},
]
